# permissions for end users to view prefetches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefetch-viewer-role
rules:
- apiGroups:
  - cache.techsquad.rocks
  resources:
  - prefetches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.techsquad.rocks
  resources:
  - prefetches/status
  verbs:
  - get
