
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.techsquad.rocks
  resources:
  - prefetches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.techsquad.rocks
  resources:
  - prefetches/status
  verbs:
  - get
  - patch
  - update
